# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ice_cooperation_limited', models.CharField(blank=True, choices=[(None, ''), ('yes-by-law', 'Yes, by Law'), ('yes-by-practice', 'Yes, by Practice'), ('no', 'No')], default=None, max_length=128, null=True, verbose_name='Is ICE cooperation limited?')),
                ('ice_cooperation_limited_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, please cite your source.')),
                ('police_policy', models.CharField(blank=True, choices=[(None, ''), ('yes-by-law', 'Yes, by Law'), ('yes-by-practice', 'Yes, by Practice'), ('no', 'No')], default=None, max_length=128, null=True, verbose_name='Is there policy for when police come into contact witth undocumented immigrants?')),
                ('police_policy_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, what?')),
                ('barriers_to_accessing_services', models.NullBooleanField()),
                ('barriers_to_accessing_services_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, what?')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('form_i247n', models.NullBooleanField(verbose_name='Form I-247N, Request for Voluntary Notification of Release of Suspected Priority Alien')),
                ('form_i247d', models.NullBooleanField(verbose_name='Form I-247D, Immigration Detainer - Request for Voluntary Action')),
                ('form_i247x', models.NullBooleanField(verbose_name='Form I-247-X, Request for Voluntary Transfer')),
                ('legal_representation', models.CharField(blank=True, choices=[('yes', 'Yes'), ('at-immigrants-expense', "At Immigrants' Expense"), ('no', 'No')], default=None, max_length=128, null=True)),
                ('restrictions_on_social_services', models.NullBooleanField(verbose_name='Are there restrictions on social services (library cards, local IDs, school registration, etc.) for undocumented immigrants?')),
                ('restrictions_on_social_services_notes', models.CharField(blank=True, default=None, max_length=2048, null=True, verbose_name='If yes, what?')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ice_cooperation_limited', models.CharField(blank=True, choices=[(None, ''), ('yes-by-law', 'Yes, by Law'), ('yes-by-practice', 'Yes, by Practice'), ('no', 'No')], default=None, max_length=128, null=True, verbose_name='Is ICE cooperation limited?')),
                ('ice_cooperation_limited_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, please cite your source.')),
                ('police_policy', models.CharField(blank=True, choices=[(None, ''), ('yes-by-law', 'Yes, by Law'), ('yes-by-practice', 'Yes, by Practice'), ('no', 'No')], default=None, max_length=128, null=True, verbose_name='Is there policy for when police come into contact witth undocumented immigrants?')),
                ('police_policy_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, what?')),
                ('barriers_to_accessing_services', models.NullBooleanField()),
                ('barriers_to_accessing_services_notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='If yes, what?')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('in_state_tuition', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('limited', 'Limited')], default=None, max_length=128, null=True, verbose_name='Can undocumented students access in-state tuition at public colleges?')),
                ('in_state_tuition_notes', models.CharField(blank=True, default=None, max_length=2048, null=True, verbose_name='If limted, please explain.')),
                ('drivers_licenses', models.NullBooleanField(verbose_name="Can undocumented immigrants get drivers' licenses?")),
                ('other_ids_available', models.NullBooleanField(verbose_name='If no, are other IDs available to them?')),
                ('other_ids_limitations', models.CharField(blank=True, max_length=2048, null=True, verbose_name='What are the limitations to these IDs (e.g. Do police recognize them as an official ID? Can they buy alcohol with this ID? etc.)?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.State'),
        ),
    ]
