# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('limited_ice_cooperation', models.CharField(blank=True, choices=[('yes-by-law', 'Yes, by law'), ('yes-in-practice', 'Yes, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True)),
                ('limited_ice_cooperation_short_answer', models.TextField(blank=True, null=True)),
                ('jails_honor_ice_detainers', models.NullBooleanField()),
                ('jails_honor_ice_detainers_short_answer', models.TextField(blank=True, null=True)),
                ('participate_287g_program', models.NullBooleanField()),
                ('participate_287g_program_short_answer', models.TextField(blank=True, null=True)),
                ('provide_legal_representation', models.NullBooleanField()),
                ('provide_legal_representation_short_answer', models.TextField(blank=True, null=True)),
                ('city_services', models.NullBooleanField()),
                ('city_services_short_answer', models.TextField(blank=True, null=True)),
                ('separate_form_of_id', models.NullBooleanField()),
                ('separate_form_of_id_short_answer', models.TextField(blank=True, null=True)),
                ('office_civic_engagement_immigrant_affairs', models.NullBooleanField()),
                ('office_civic_engagement_immigrant_affairs_short_answer', models.TextField(blank=True, null=True)),
                ('other_policies_and_services', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.State'),
        ),
    ]
