# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:31
from __future__ import unicode_literals
from django.db import migrations
from django.conf import settings
import os


def populate_state(apps, schema_editor):
    from django.contrib.gis.utils import LayerMapping
    
    State = apps.get_model('map', 'State')
    state_mapping = LayerMapping(State, os.path.join(settings.BASE_DIR, 'geography/geodata/states/cb_2015_us_state_500k/cb_2015_us_state_500k.shp'), {'name': 'NAME', 'geom': 'MULTIPOLYGON'})
    state_mapping.save(verbose=True)


def remove_state(apps, schema_editor):
    State = apps.get_model('geography', 'State')
    State.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_state, reverse_code=remove_state)
    ]
