# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_populate_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='isga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='city',
            name='isga_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='ice_contracts',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='ice_contracts_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='isga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='isga_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_honor_ice_detainers',
            field=models.CharField(blank=True, choices=[('yes-by-law', 'Yes, by law'), ('yes-in-practice', 'Yes, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_honor_ice_detainers_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_prohibit_inquiries',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_prohibit_inquiries_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='other_policies_and_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='permitting_policies',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='permitting_policies_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='preventing_policies',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='preventing_policies_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='barrier',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='barrier_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='drivers_license',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='drivers_license_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='ice_contracts',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='ice_contracts_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='in_state_tuition',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='in_state_tuition_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='isga',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='isga_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='limited_ice_cooperation',
            field=models.CharField(blank=True, choices=[('yes-by-law', 'Yes, by law'), ('yes-in-practice', 'Yes, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='limited_ice_cooperation_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='other_policies_and_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='provide_legal_representation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='state',
            name='provide_legal_representation_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
