# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:23
from __future__ import unicode_literals
from django.db import migrations, models
import random

def populate_bogus_data(apps, schema_editor):

    County = apps.get_model('map', 'County')

    random_counties = County.objects.order_by('?')[0:200]

    for county in random_counties:

        county.limited_ice_cooperation = random.choice(['yes-by-law', 'yes-in-practice', 'unlimited'])
        county.save()


def undo_bogus_data(apps, schema_editor):

    County = apps.get_model('map', 'County')
    County.objects.filter(limited_ice_cooperation__is_null=False).update(limited_ice_cooperation=None)



class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_populate_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='limited_ice_cooperation',
            field=models.CharField(blank=True, choices=[('yes-by-law', 'Yes, by law'), ('yes-in-practice', 'Yes, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='limited_ice_cooperation_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(populate_bogus_data, reverse_code=undo_bogus_data)
    ]
