# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:45
from __future__ import unicode_literals
from django.db import migrations, models
from django.template.defaultfilters import slugify



def populate_slugs(apps, schema_editor):

    City, County, State = [apps.get_model('map', turf) for turf in ['City', 'County', 'State']]

    for city in City.objects.select_related('state').defer('geom', 'state__geom').all():
        city.slug = slugify('-'.join([city.name, city.state.name]))
        city.save()

    for county in County.objects.select_related('state').defer('geom', 'state__geom').all():
        county.slug = slugify('-'.join([county.name, 'county', county.state.name]))
        county.save()

    for state in State.objects.defer('geom').all():
        state.slug = slugify(state.name)
        state.save()


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_populate_cis_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=128),
        ),
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=128),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=128),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop)
    ]
