# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20170210_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='isga_short_answer',
        ),
        migrations.RemoveField(
            model_name='city',
            name='office_civic_engagement_immigrant_affairs',
        ),
        migrations.RemoveField(
            model_name='city',
            name='office_civic_engagement_immigrant_affairs_short_answer',
        ),
        migrations.RemoveField(
            model_name='city',
            name='policies_against_profiling',
        ),
        migrations.RemoveField(
            model_name='city',
            name='policies_against_profiling_short_answer',
        ),
    ]
