# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20170217_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_council_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
