# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20170316_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='local_effort_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
