# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_state_local_effort_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='local_effort_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='local_effort',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='county',
            name='local_effort_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='local_effort_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
