# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_city_isga_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='participate_287g_program_source',
        ),
    ]
