# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20170403_2234'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='city',
        #     name='participate_287g_program_short_answer',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
