# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_state_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='county',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
