# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20170405_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='jails_honor_ice_detainers',
            field=models.CharField(blank=True, choices=[('no-by-law', 'No, by law'), ('no-in-practice', 'No, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True),
        ),
    ]
