# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20170405_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='jails_honor_ice_detainers',
            field=models.CharField(blank=True, choices=[('yes-by-law', 'Yes, by law'), ('yes-in-practice', 'Yes, in practice (informal)'), ('unlimited', 'Mark if there is unlimited ICE cooperation'), (None, 'Information N/A')], max_length=128, null=True),
        ),
    ]
