# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20170405_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='resources',
        ),
    ]
