# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_remove_state_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='local_effort_short_answer',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='local_effort_short_answer',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='local_effort_short_answer',
            new_name='resources',
        ),
    ]
