# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20170405_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='ice_contracts_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='isga_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_honor_ice_detainers_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='jails_prohibit_inquiries_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='local_effort_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='other_policies_and_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='permitting_policies_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='preventing_policies_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
