# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_state_local_effort_short_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='barrier_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='drivers_license_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='ice_contracts_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='in_state_tuition_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='isga_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='limited_ice_cooperation_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='other_policies_and_services_short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='other_policies_and_services_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='policies_against_profiling_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='provide_legal_representation_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
